<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UnidadMedidasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $unidad_medidas = [
            ['unidad_medida_singular'	=> 'Academia',	'unidad_medida_plural'	=> 'Academias'],
            ['unidad_medida_singular'	=> 'Acceso',	'unidad_medida_plural'	=> 'Accesos'],
            ['unidad_medida_singular'	=> 'Acción',	'unidad_medida_plural'	=> 'Acciones'],
            ['unidad_medida_singular'	=> 'Acompañamiento',	'unidad_medida_plural'	=>'	Acompañamientos'],
            ['unidad_medida_singular'	=> 'Acreditación',	'unidad_medida_plural'	=>'	Acreditaciones'],
            ['unidad_medida_singular'	=> 'Acta',	'unidad_medida_plural'	=> 'Actas'],
            ['unidad_medida_singular'	=> 'Actividad',	'unidad_medida_plural'	=> 'Actividades'],
            ['unidad_medida_singular'	=> 'Acto',	'unidad_medida_plural'	=> 'Actos'],
            ['unidad_medida_singular'	=> 'Actuación',	'unidad_medida_plural'	=> 'Actuaciones'],
            ['unidad_medida_singular'	=> 'Actualización',	'unidad_medida_plural'	=>' Actualizaciones'],
            ['unidad_medida_singular'	=> 'Acuerdo',	'unidad_medida_plural'	=> 'Acuerdos'],
            ['unidad_medida_singular'	=> 'Adecuación',	'unidad_medida_plural'	=> 'Adecuaciones'],
            ['unidad_medida_singular'	=> 'Adquisición',	'unidad_medida_plural'	=> 'Adquisiciones'],
            ['unidad_medida_singular'	=> 'Adulto',	'unidad_medida_plural'	=> 'Adultos'],
            ['unidad_medida_singular'	=> 'Afiliación',	'unidad_medida_plural'	=> 'Afiliaciones'],
            ['unidad_medida_singular'	=> 'Agenda',	'unidad_medida_plural'	=> 'Agendas'],
            ['unidad_medida_singular'	=> 'Ajuste',	'unidad_medida_plural'	=> 'Ajustes'],
            ['unidad_medida_singular'	=> 'Alcance',	'unidad_medida_plural'	=> 'Alcances'],
            ['unidad_medida_singular'	=> 'Alerta',	'unidad_medida_plural'	=> 'Alertas'],
            ['unidad_medida_singular'	=> 'Alta',	'unidad_medida_plural'	=> 'Altas'],
            ['unidad_medida_singular'	=> 'Alumno',	'unidad_medida_plural'	=> 'Alumnos'],
            ['unidad_medida_singular'	=> 'Amplitud',	'unidad_medida_plural'	=> 'Amplitudes'],
            ['unidad_medida_singular'	=> 'Análisis',	'unidad_medida_plural'	=> 'Análisis'],
            ['unidad_medida_singular'	=> 'Anexo Femenil',	'unidad_medida_plural'	=> 'Anexos Femeniles'],
            ['unidad_medida_singular'	=> 'Animal',	'unidad_medida_plural'	=> 'Animales'],
            ['unidad_medida_singular'	=> 'Anteproyecto',	'unidad_medida_plural'	=> 'Anteproyectos'],
            ['unidad_medida_singular'	=> 'Año',	'unidad_medida_plural'	=>'	Años'],
            ['unidad_medida_singular'	=> 'Apertura',	'unidad_medida_plural'	=> 'Aperturas'],
            ['unidad_medida_singular'	=> 'Aplicativo',	'unidad_medida_plural'	=> 'Aplicativos'],
            ['unidad_medida_singular'	=> 'Aportación',	'unidad_medida_plural'	=> 'Aportaciones'],
            ['unidad_medida_singular'	=> 'Apoyo',	'unidad_medida_plural'	=> 'Apoyos'],
            ['unidad_medida_singular'	=> 'Árbol',	'unidad_medida_plural'	=> 'Árboles'],
            ['unidad_medida_singular'	=> 'Arco',	'unidad_medida_plural'	=> 'Arcos'],
            ['unidad_medida_singular'	=> 'Arcos Rfid',	'unidad_medida_plural'	=> 'Arcos RFID'],
            ['unidad_medida_singular'	=> 'Área',	'unidad_medida_plural'	=>'	Áreas'],
            ['unidad_medida_singular'	=> 'Armas De Fuego','unidad_medida_plural'	=> 'Armas De Fuego'],
            ['unidad_medida_singular'	=> 'Armonización',	'unidad_medida_plural'	=> 'Armonizaciones'],
            ['unidad_medida_singular'	=> 'Artesano',	'unidad_medida_plural'	=> 'Artesanos'],
            ['unidad_medida_singular'	=> 'Artículo',	'unidad_medida_plural'	=> 'Artículos'],
            ['unidad_medida_singular'	=> 'Artista',	'unidad_medida_plural'	=> 'Artistas'],
            ['unidad_medida_singular'	=> 'Asesor',	'unidad_medida_plural'	=> 'Asesors'],
            ['unidad_medida_singular'	=> 'Asesoría',	'unidad_medida_plural'	=> 'Asesorías'],
            ['unidad_medida_singular'	=> 'Asesoría Y Consulta', 'unidad_medida_plural'	=>'	Asesoría Y Consultas'],
            ['unidad_medida_singular'	=> 'Asignatura',	'unidad_medida_plural'	=>'	Asignaturas'],
            ['unidad_medida_singular'	=> 'Asistencia',	'unidad_medida_plural'	=>'	Asistencias'],
            ['unidad_medida_singular'	=> 'Asistente',	'unidad_medida_plural'	=>'	Asistentes'],
            ['unidad_medida_singular'	=> 'Asm',	'unidad_medida_plural'	=>'	Asms'],
            ['unidad_medida_singular'	=> 'Aspirante',	'unidad_medida_plural'	=>'	Aspirantes'],
            ['unidad_medida_singular'	=> 'Asunto',	'unidad_medida_plural'	=>'	Asuntos'],
            ['unidad_medida_singular'	=> 'Atención',	'unidad_medida_plural'	=>'	Atenciones'],
            ['unidad_medida_singular'	=> 'Atleta',	'unidad_medida_plural'	=>'	Atletas'],
            ['unidad_medida_singular'	=> 'Audiencia',	'unidad_medida_plural'	=>'	Audiencias'],
            ['unidad_medida_singular'	=> 'Auditoria',	'unidad_medida_plural'	=>'	Auditorías'],
            ['unidad_medida_singular'	=> 'Aula',	'unidad_medida_plural'	=>'	Aulas'],
            ['unidad_medida_singular'	=> 'Autoevaluación',	'unidad_medida_plural'	=>'	Autoevaluaciones'],
            ['unidad_medida_singular'	=> 'Autoridad',	'unidad_medida_plural'	=>'	Autoridades'],
            ['unidad_medida_singular'	=> 'Avalúo',	'unidad_medida_plural'	=>'	Avalúos'],
            ['unidad_medida_singular'	=> 'Avance',	'unidad_medida_plural'	=>'	Avances'],
            ['unidad_medida_singular'	=> 'Averiguación',	'unidad_medida_plural'	=>'	Averiguaciones'],
            ['unidad_medida_singular'	=> 'Aviso',	'unidad_medida_plural'	=>'	Avisos'],
            ['unidad_medida_singular'	=> 'Ayuda Funcional',	'unidad_medida_plural'	=>'	Ayuda Funcionales'],
            ['unidad_medida_singular'	=> 'Ayuda Legal',	'unidad_medida_plural'	=>'	Ayuda Legales'],
            ['unidad_medida_singular'	=> 'Ayuda Técnica',	'unidad_medida_plural'	=>'	Ayuda Técnicas'],
            ['unidad_medida_singular'	=> 'Baja',	'unidad_medida_plural'	=>'	Bajas'],
            ['unidad_medida_singular'	=> 'Baño',	'unidad_medida_plural'	=>'	Baños'],
            ['unidad_medida_singular'	=> 'Base De Datos',	'unidad_medida_plural'	=>'	Base De Datos'],
            ['unidad_medida_singular'	=> 'Beca', 'unidad_medida_plural' => 'Becas'],
            ['unidad_medida_singular'	=> 'Becario', 'unidad_medida_plural' =>' Becarios'],
            ['unidad_medida_singular'	=> 'Beneficiario', 'unidad_medida_plural' => 'Beneficiarios'],
            ['unidad_medida_singular'	=> 'Beneficios', 'unidad_medida_plural' => 'Beneficios'],
            ['unidad_medida_singular'	=> 'Biblioteca', 'unidad_medida_plural'	=> 'Bibliotecas'],
            ['unidad_medida_singular'	=> 'Bien De Capital', 'unidad_medida_plural'	=>'	Bien De Capital'],
            ['unidad_medida_singular'	=> 'Bienes', 'unidad_medida_plural'	=>'	Bienes'],
            ['unidad_medida_singular'	=> 'Boletín', 'unidad_medida_plural' => 'Boletines'],
            ['unidad_medida_singular'	=> 'Brigada', 'unidad_medida_plural' => 'Brigadas'],
            ['unidad_medida_singular'	=> 'Brigadista', 'unidad_medida_plural'	=> 'Brigadistas'],
            ['unidad_medida_singular'	=> 'Buzón', 'unidad_medida_plural'	=>'	Buzones'],
            ['unidad_medida_singular'	=> 'Cadena Productiva', 'unidad_medida_plural'	=>'	Cadenas Productivas'],
            ['unidad_medida_singular'	=> 'Cálculo', 'unidad_medida_plural'	=>'	Cálculos'],
            ['unidad_medida_singular'	=> 'Calendario', 'unidad_medida_plural'	=>'	Calendarios'],
            ['unidad_medida_singular'	=> 'Calificación', 'unidad_medida_plural'	=>'	Calificaciones'],
            ['unidad_medida_singular'	=> 'Cama', 'unidad_medida_plural'	=>'	Camas'],
            ['unidad_medida_singular'	=> 'Cámaras', 'unidad_medida_plural'	=>'	Cámaras'],
            ['unidad_medida_singular'	=> 'Campamento', 'unidad_medida_plural'	=>'	Campamentos'],
            ['unidad_medida_singular'	=> 'Campaña', 'unidad_medida_plural'	=>'	Campañas'],
            ['unidad_medida_singular'	=> 'Campesino', 'unidad_medida_plural'	=>'	Campesinos'],
            ['unidad_medida_singular'	=> 'Canalización', 'unidad_medida_plural'	=>'	Canalizaciones'],
            ['unidad_medida_singular'	=> 'Canje', 'unidad_medida_plural'	=>'	Canjes'],
            ['unidad_medida_singular'	=> 'Cantidad De Entes',	'unidad_medida_plural'	=>'	Cantidad De Entes'],
            ['unidad_medida_singular'	=> 'Capacidad',	'unidad_medida_plural'	=>'	Capacidades'],
            ['unidad_medida_singular'	=> 'Capacitación', 'unidad_medida_plural'	=>'	Capacitaciones'],
            ['unidad_medida_singular'	=> 'Cápsula', 'unidad_medida_plural'	=>'	Cápsulas'],
            ['unidad_medida_singular'	=> 'Captación De Armas',	'unidad_medida_plural'	=>'	Captación de Armas'],
            ['unidad_medida_singular'	=> 'Caravana', 'unidad_medida_plural'	=>'	Caravanas'],
            ['unidad_medida_singular'	=> 'Carencia', 'unidad_medida_plural'	=>'	Carencias'],
            ['unidad_medida_singular'	=> 'Carpeta', 'unidad_medida_plural'	=>'	Carpetas'],
            ['unidad_medida_singular'	=> 'Carrera', 'unidad_medida_plural'	=>'	Carreras'],
            ['unidad_medida_singular'	=> 'Carta',	'unidad_medida_plural'	=>'	Cartas'],
            ['unidad_medida_singular'	=> 'Carta Presentación',	'unidad_medida_plural'	=>'	Cartas de Presentación'],
            ['unidad_medida_singular'	=> 'Cartel',	'unidad_medida_plural'	=>'	Carteles'],
            ['unidad_medida_singular'	=> 'Caso',	'unidad_medida_plural'	=>'	Casos'],
            ['unidad_medida_singular'	=> 'Catálogo',	'unidad_medida_plural'	=>'	Catálogos'],
            ['unidad_medida_singular'	=> 'Cátedra',	'unidad_medida_plural'	=>'	Cátedras'],
            ['unidad_medida_singular'	=> 'Cédula',	'unidad_medida_plural'	=>'	Cédulas'],
            ['unidad_medida_singular'	=> 'Centro',	'unidad_medida_plural'	=>'	Centros'],
            ['unidad_medida_singular'	=> 'Centro De Internamiento',	'unidad_medida_plural'	=>'	Centros De Internamiento'],
            ['unidad_medida_singular'	=> 'Centro De Monitoreo',	'unidad_medida_plural'	=>'	Centro De Monitoreo'],
            ['unidad_medida_singular'	=> 'Centro Deportivo',	'unidad_medida_plural'	=>'	Centro Deportivos'],
            ['unidad_medida_singular'	=> 'Ceremonia',	'unidad_medida_plural'	=>'	Ceremonias'],
            ['unidad_medida_singular'	=> 'Certificación',	'unidad_medida_plural'	=>'	Certificaciones'],
            ['unidad_medida_singular'	=> 'Certificado',	'unidad_medida_plural'	=>'	Certificados'],
            ['unidad_medida_singular'	=> 'Cirugía',	'unidad_medida_plural'	=>'	Cirugías'],
            ['unidad_medida_singular'	=> 'Cisterna',	'unidad_medida_plural'	=>'	Cisternas'],
            ['unidad_medida_singular'	=> 'Ciudadano',	'unidad_medida_plural'	=>'	Ciudadanos'],
            ['unidad_medida_singular'	=> 'Cliente',	'unidad_medida_plural'	=>'	Clientes'],
            ['unidad_medida_singular'	=> 'Cobertura',	'unidad_medida_plural'	=>'	Coberturas'],
            ['unidad_medida_singular'	=> 'Coeficiente',	'unidad_medida_plural'	=>'	Coeficientes'],
            ['unidad_medida_singular'	=> 'Comercialización',	'unidad_medida_plural'	=>'	Comercializaciones'],
            ['unidad_medida_singular'	=> 'Comisión',	'unidad_medida_plural'	=>'	Comisiones'],
            ['unidad_medida_singular'	=> 'Comité',	'unidad_medida_plural'	=>'	Comités'],
            ['unidad_medida_singular'	=> 'Componente',	'unidad_medida_plural'	=>'	Componentes'],
            ['unidad_medida_singular'	=> 'Compromiso',	'unidad_medida_plural'	=>'	Compromisos'],
            ['unidad_medida_singular'	=> 'Comunidad',	'unidad_medida_plural'	=>'	Comunidades'],
            ['unidad_medida_singular'	=> 'Concepto De Obra',	'unidad_medida_plural'	=>'	Concepto De Obras'],
            ['unidad_medida_singular'	=> 'Concertación',	'unidad_medida_plural'	=>'	Concertaciones'],
            ['unidad_medida_singular'	=> 'Concierto',	'unidad_medida_plural'	=>'	Conciertos'],
            ['unidad_medida_singular'	=> 'Conciliación',	'unidad_medida_plural'	=>'	Conciliaciones'],
            ['unidad_medida_singular'	=> 'Concurso',	'unidad_medida_plural'	=>'	Concursos'],
            ['unidad_medida_singular'	=> 'Condonación',	'unidad_medida_plural'	=>'	Condonaciones'],
            ['unidad_medida_singular'	=> 'Conferencia',	'unidad_medida_plural'	=>'	Conferencias'],
            ['unidad_medida_singular'	=> 'Congreso',	'unidad_medida_plural'	=>'	Congresos'],
            ['unidad_medida_singular'	=> 'Consejo',	'unidad_medida_plural'	=>'	Conesejos'],
            ['unidad_medida_singular'	=> 'Constancia',	'unidad_medida_plural'	=>'	Conestancias'],
            ['unidad_medida_singular'	=> 'Construcción',	'unidad_medida_plural'	=>'	Conestrucciones'],
            ['unidad_medida_singular'	=> 'Consulta',	'unidad_medida_plural'	=>'	Consultas'],
            ['unidad_medida_singular'	=> 'Consultoría',	'unidad_medida_plural'	=>'	Consultorías'],
            ['unidad_medida_singular'	=> 'Consultorio',	'unidad_medida_plural'	=>'	Consultorios'],
            ['unidad_medida_singular'	=> 'Contra Recibo',	'unidad_medida_plural'	=>'	Contra Recibos'],
            ['unidad_medida_singular'	=> 'Contrato',	'unidad_medida_plural'	=>'	Contratos'],
            ['unidad_medida_singular'	=> 'Contribuyente',	'unidad_medida_plural'	=>'	Contribuyentes'],
            ['unidad_medida_singular'	=> 'Controversia',	'unidad_medida_plural'	=>'	Controversias'],
            ['unidad_medida_singular'	=> 'Convenio',	'unidad_medida_plural'	=>'	Convenios'],
            ['unidad_medida_singular'	=> 'Convivencia',	'unidad_medida_plural'	=>'	Convivencias'],
            ['unidad_medida_singular'	=> 'Convocatoria',	'unidad_medida_plural'	=>'	Convocatorias'],
            ['unidad_medida_singular'	=> 'Coordinación',	'unidad_medida_plural'	=>'	Coordinaciones'],
            ['unidad_medida_singular'	=> 'Corrupción',	'unidad_medida_plural'	=>'	Corrupciones'],
            ['unidad_medida_singular'	=> 'Costo',	'unidad_medida_plural'	=>'	Costos'],
            ['unidad_medida_singular'	=> 'Cotización',	'unidad_medida_plural'	=>'	Cotizaciones'],
            ['unidad_medida_singular'	=> 'Creador',	'unidad_medida_plural'	=>'	Creadores'],
            ['unidad_medida_singular'	=> 'Credencial',	'unidad_medida_plural'	=>'	Credenciales'],
            ['unidad_medida_singular'	=> 'Crédito',	'unidad_medida_plural'	=>'	Créditos'],
            ['unidad_medida_singular'	=> 'Cría',	'unidad_medida_plural'	=>'	Crías'],
            ['unidad_medida_singular'	=> 'Criterio',	'unidad_medida_plural'	=>'	Criterios'],
            ['unidad_medida_singular'	=> 'Cuarto',	'unidad_medida_plural'	=>'	Cuartos'],
            ['unidad_medida_singular'	=> 'Cuenta Pública',	'unidad_medida_plural'	=>'	Cuenta Públicas'],
            ['unidad_medida_singular'	=> 'Cuestionario',	'unidad_medida_plural'	=>'	Cuestionarios'],
            ['unidad_medida_singular'	=> 'Curso',	'unidad_medida_plural'	=>'	Cursos'],
            ['unidad_medida_singular'	=> 'Curso Taller',	'unidad_medida_plural'	=>'	Cursos Taller'],
            ['unidad_medida_singular'	=> 'Declaración',	'unidad_medida_plural'	=>'	Declaraciones'],
            ['unidad_medida_singular'	=> 'Declaratoria',	'unidad_medida_plural'	=>'	Declaratorias'],
            ['unidad_medida_singular'	=> 'Decreto',	'unidad_medida_plural'	=>'	Decretos'],
            ['unidad_medida_singular'	=> 'Defunción',	'unidad_medida_plural'	=>'	Defunciones'],
            ['unidad_medida_singular'	=> 'Delincuente',	'unidad_medida_plural'	=>'	Delincuentes'],
            ['unidad_medida_singular'	=> 'Delito',	'unidad_medida_plural'	=>'	Delitos'],
            ['unidad_medida_singular'	=> 'Demostración',	'unidad_medida_plural'	=>'	Demostraciones'],
            ['unidad_medida_singular'	=> 'Denuncia',	'unidad_medida_plural'	=>'	Denuncias'],
            ['unidad_medida_singular'	=> 'Dependencia',	'unidad_medida_plural'	=>'	Dependencias'],
            ['unidad_medida_singular'	=> 'Deportista',	'unidad_medida_plural'	=>'	Deportistas'],
            ['unidad_medida_singular'	=> 'Desarrollo',	'unidad_medida_plural'	=>'	Desarrollos'],
            ['unidad_medida_singular'	=> 'Desayunador',	'unidad_medida_plural'	=>'	Desayunadors'],
            ['unidad_medida_singular'	=> 'Desayuno',	'unidad_medida_plural'	=>'	Desayunos'],
            ['unidad_medida_singular'	=> 'Descarga',	'unidad_medida_plural'	=>'	Descargas'],
            ['unidad_medida_singular'	=> 'Despensa',	'unidad_medida_plural'	=>'	Despensas'],
            ['unidad_medida_singular'	=> 'Detección',	'unidad_medida_plural'	=>'	Detecciones'],
            ['unidad_medida_singular'	=> 'Detenido',	'unidad_medida_plural'	=>'	Detenidos'],
            ['unidad_medida_singular'	=> 'Día',	'unidad_medida_plural'	=>'	Días'],
            ['unidad_medida_singular'	=> 'Diagnóstico',	'unidad_medida_plural'	=>'	Diagnósticos'],
            ['unidad_medida_singular'	=> 'Dictamen',	'unidad_medida_plural'	=>'	Dictámenes'],
            ['unidad_medida_singular'	=> 'Difusión',	'unidad_medida_plural'	=>'	Difusiones'],
            ['unidad_medida_singular'	=> 'Diligencia',	'unidad_medida_plural'	=>'	Diligencias'],
            ['unidad_medida_singular'	=> 'Dinero',	'unidad_medida_plural'	=>'	Dinero'],
            ['unidad_medida_singular'	=> 'Diplomado',	'unidad_medida_plural'	=>'	Diplomados'],
            ['unidad_medida_singular'	=> 'Disciplina',	'unidad_medida_plural'	=>'	Disciplinas'],
            ['unidad_medida_singular'	=> 'Diseño',	'unidad_medida_plural'	=>'	Diseños'],
            ['unidad_medida_singular'	=> 'Dispositivo',	'unidad_medida_plural'	=>'	Dispositivos'],
            ['unidad_medida_singular'	=> 'Distintivo',	'unidad_medida_plural'	=>'	Distintivos'],
            ['unidad_medida_singular'	=> 'Docente',	'unidad_medida_plural'	=>'	Docentes'],
            ['unidad_medida_singular'	=> 'Documental',	'unidad_medida_plural'	=>'	Documentales'],
            ['unidad_medida_singular'	=> 'Documento',	'unidad_medida_plural'	=>'	Documentos'],
            ['unidad_medida_singular'	=> 'Dólar',	'unidad_medida_plural'	=>'	Dólares'],
            ['unidad_medida_singular'	=> 'Donación',	'unidad_medida_plural'	=>'	Donaciones'],
            ['unidad_medida_singular'	=> 'Dotación',	'unidad_medida_plural'	=>'	Dotaciones'],
            ['unidad_medida_singular'	=> 'Edición',	'unidad_medida_plural'	=>'	Ediciones'],
            ['unidad_medida_singular'	=> 'Edificio',	'unidad_medida_plural'	=>'	Edificios'],
            ['unidad_medida_singular'	=> 'Educando',	'unidad_medida_plural'	=>'	Educandos'],
            ['unidad_medida_singular'	=> 'Egresado',	'unidad_medida_plural'	=>'	Egresados'],
            ['unidad_medida_singular'	=> 'Ejemplar',	'unidad_medida_plural'	=>'	Ejemplares'],
            ['unidad_medida_singular'	=> 'Elección',	'unidad_medida_plural'	=>'	Elecciones'],
            ['unidad_medida_singular'	=> 'Elemento',	'unidad_medida_plural'	=>'	Elementos'],
            ['unidad_medida_singular'	=> 'Embajador',	'unidad_medida_plural'	=>'	Embajadores'],
            ['unidad_medida_singular'	=> 'Emergencia',	'unidad_medida_plural'	=>'	Emergencias'],
            ['unidad_medida_singular'	=> 'Emisión',	'unidad_medida_plural'	=>'	Emisiones'],
            ['unidad_medida_singular'	=> 'Empleado',	'unidad_medida_plural'	=>'	Empleados'],
            ['unidad_medida_singular'	=> 'Empleo',	'unidad_medida_plural'	=>'	Empleos'],
            ['unidad_medida_singular'	=> 'Emprendedor',	'unidad_medida_plural'	=>'	Emprendedores'],
            ['unidad_medida_singular'	=> 'Empresa',	'unidad_medida_plural'	=>'	Empresas'],
            ['unidad_medida_singular'	=> 'Encuesta',	'unidad_medida_plural'	=>'	Encuestas'],
            ['unidad_medida_singular'	=> 'Enlace',	'unidad_medida_plural'	=>'	Enlaces'],
            ['unidad_medida_singular'	=> 'Ente Público',	'unidad_medida_plural'	=>'	Entes Públicos'],
            ['unidad_medida_singular'	=> 'Entidad',	'unidad_medida_plural'	=>'	Entidades'],
            ['unidad_medida_singular'	=> 'Entrenador',	'unidad_medida_plural'	=>'	Entrenadores'],
            ['unidad_medida_singular'	=> 'Entrevista',	'unidad_medida_plural'	=>'	Entrevistas'],
            ['unidad_medida_singular'	=> 'Equipamiento',	'unidad_medida_plural'	=>'	Equipamientos'],
            ['unidad_medida_singular'	=> 'Equipo',	'unidad_medida_plural'	=>'	Equipos'],
            ['unidad_medida_singular'	=> 'Equipo Tecnológico',	'unidad_medida_plural'	=>'	Equipos Tecnológicos'],
            ['unidad_medida_singular'	=> 'Equivalencia',	'unidad_medida_plural'	=>'	Equivalencias'],
            ['unidad_medida_singular'	=> 'Escuela',	'unidad_medida_plural'	=>'	Escuelas'],
            ['unidad_medida_singular'	=> 'Espacio',	'unidad_medida_plural'	=>'	Espacios'],
            ['unidad_medida_singular'	=> 'Especialidad',	'unidad_medida_plural'	=>'	Especialidades'],
            ['unidad_medida_singular'	=> 'Especie',	'unidad_medida_plural'	=>'	Especies'],
            ['unidad_medida_singular'	=> 'Esquema',	'unidad_medida_plural'	=>'	Esquemas'],
            ['unidad_medida_singular'	=> 'Establecimiento',	'unidad_medida_plural'	=>'	Establecimientos'],
            ['unidad_medida_singular'	=> 'Estación De Monitoreo',	'unidad_medida_plural'	=>'	Estaciones de Monitoreo'],
            ['unidad_medida_singular'	=> 'Estadística',	'unidad_medida_plural'	=>'	Estadísticas'],
            ['unidad_medida_singular'	=> 'Estado Financiero',	'unidad_medida_plural'	=>'	Estados Financieros'],
            ['unidad_medida_singular'	=> 'Estimación',	'unidad_medida_plural'	=>'	Estimaciones'],
            ['unidad_medida_singular'	=> 'Estímulo',	'unidad_medida_plural'	=>'	Estímulos'],
            ['unidad_medida_singular'	=> 'Estrategia',	'unidad_medida_plural'	=>'	Estrategias'],
            ['unidad_medida_singular'	=> 'Estructura',	'unidad_medida_plural'	=>'	Estructuras'],
            ['unidad_medida_singular'	=> 'Estudiante',	'unidad_medida_plural'	=>'	Estudiantes'],
            ['unidad_medida_singular'	=> 'Estudio',	'unidad_medida_plural'	=>'	Estudios'],
            ['unidad_medida_singular'	=> 'Estufa',	'unidad_medida_plural'	=>'	Estufas'],
            ['unidad_medida_singular'	=> 'Etapa',	'unidad_medida_plural'	=>'	Etapas'],
            ['unidad_medida_singular'	=> 'Evaluación',	'unidad_medida_plural'	=>'	Evaluaciones'],
            ['unidad_medida_singular'	=> 'Evento',	'unidad_medida_plural'	=>'	Eventos'],
            ['unidad_medida_singular'	=> 'Examen',	'unidad_medida_plural'	=>'	Examens'],
            ['unidad_medida_singular'	=> 'Exhorto',	'unidad_medida_plural'	=>'	Exhortos'],
            ['unidad_medida_singular'	=> 'Expediente', 'unidad_medida_plural'	=>'	Expedientes'],
            ['unidad_medida_singular'	=> 'Expo Venta', 'unidad_medida_plural'	=>'	Expo Ventas'],
            ['unidad_medida_singular'	=> 'Exposición', 'unidad_medida_plural'	=>'	Exposiciones'],
            ['unidad_medida_singular'	=> 'Extensión Universitaria',	'unidad_medida_plural'	=>'	Extensiones Universitarias'],
            ['unidad_medida_singular'	=> 'Familia',	'unidad_medida_plural'	=>'	Familias'],
            ['unidad_medida_singular'	=> 'Fase',	'unidad_medida_plural'	=>'	Fases'],
            ['unidad_medida_singular'	=> 'Feria',	'unidad_medida_plural'	=>'	Ferias'],
            ['unidad_medida_singular'	=> 'Festival',	'unidad_medida_plural'	=>'	Festivales'],
            ['unidad_medida_singular'	=> 'Ficha',	'unidad_medida_plural'	=>'	Fichas'],
            ['unidad_medida_singular'	=> 'Financiamiento',	'unidad_medida_plural'	=>'	Financiamientos'],
            ['unidad_medida_singular'	=> 'Finiquito',	'unidad_medida_plural'	=>'	Finiquitos'],
            ['unidad_medida_singular'	=> 'Folleto',	'unidad_medida_plural'	=>'	Folletos'],
            ['unidad_medida_singular'	=> 'Forma',	'unidad_medida_plural'	=>'	Formas'],
            ['unidad_medida_singular'	=> 'Formación',	'unidad_medida_plural'	=>'	Formaciones'],
            ['unidad_medida_singular'	=> 'Formato',	'unidad_medida_plural'	=>'	Formatos'],
            ['unidad_medida_singular'	=> 'Foro',	'unidad_medida_plural'	=>'	Foros'],
            ['unidad_medida_singular'	=> 'Fracción',	'unidad_medida_plural'	=>'	Fracciones'],
            ['unidad_medida_singular'	=> 'Fuente',	'unidad_medida_plural'	=>'	Fuentes'],
            ['unidad_medida_singular'	=> 'Función',	'unidad_medida_plural'	=>'	Funciones'],
            ['unidad_medida_singular'	=> 'Gasto',	'unidad_medida_plural'	=>'	Gastos'],
            ['unidad_medida_singular'	=> 'Gasto Médico',	'unidad_medida_plural'	=>'	Gastos Médicos'],
            ['unidad_medida_singular'	=> 'Gestión',	'unidad_medida_plural'	=>'	Gestiones'],
            ['unidad_medida_singular'	=> 'Gira',	'unidad_medida_plural'	=>'	Giras'],
            ['unidad_medida_singular'	=> 'Glosa',	'unidad_medida_plural'	=>'	Glosas'],
            ['unidad_medida_singular'	=> 'Gps',	'unidad_medida_plural'	=>'	Gps'],
            ['unidad_medida_singular'	=> 'Grabación',	'unidad_medida_plural'	=>'	Grabaciones'],
            ['unidad_medida_singular'	=> 'Grado',	'unidad_medida_plural'	=>'	Grados'],
            ['unidad_medida_singular'	=> 'Grupo',	'unidad_medida_plural'	=>'	Grupos'],
            ['unidad_medida_singular'	=> 'Guía',	'unidad_medida_plural'	=>'	Guías'],
            ['unidad_medida_singular'	=> 'Habitante',	'unidad_medida_plural'	=>'	Habitantes'],
            ['unidad_medida_singular'	=> 'Hectárea',	'unidad_medida_plural'	=>'	Hectáreas'],
            ['unidad_medida_singular'	=> 'Herramienta',	'unidad_medida_plural'	=>'	Herramientas'],
            ['unidad_medida_singular'	=> 'Hogar',	'unidad_medida_plural'	=>'	Hogares'],
            ['unidad_medida_singular'	=> 'Hoja',	'unidad_medida_plural'	=>'	Hojas'],
            ['unidad_medida_singular'	=> 'Hombre',	'unidad_medida_plural'	=>'	Hombres'],
            ['unidad_medida_singular'	=> 'Hora',	'unidad_medida_plural'	=>'	Horas'],
            ['unidad_medida_singular'	=> 'Hotel',	'unidad_medida_plural'	=>'	Hoteles'],
            ['unidad_medida_singular'	=> 'Huerto',	'unidad_medida_plural'	=>'	Huertos'],
            ['unidad_medida_singular'	=> 'Identificación',	'unidad_medida_plural'	=>'	Identificaciones'],
            ['unidad_medida_singular'	=> 'Implementación',	'unidad_medida_plural'	=>'	Implementaciones'],
            ['unidad_medida_singular'	=> 'Impresión',	'unidad_medida_plural'	=>'	Impresiones'],
            ['unidad_medida_singular'	=> 'Incendio',	'unidad_medida_plural'	=>'	Incendios'],
            ['unidad_medida_singular'	=> 'Incentivo',	'unidad_medida_plural'	=>'	Incentivos'],
            ['unidad_medida_singular'	=> 'Incidencia',	'unidad_medida_plural'	=>'	Incidencias'],
            ['unidad_medida_singular'	=> 'Incremento',	'unidad_medida_plural'	=>'	Incrementos'],
            ['unidad_medida_singular'	=> 'Indicador',	'unidad_medida_plural'	=>'	Indicadores'],
            ['unidad_medida_singular'	=> 'Índice',	'unidad_medida_plural'	=>'	Índices'],
            ['unidad_medida_singular'	=> 'Industria',	'unidad_medida_plural'	=>'	Industrias'],
            ['unidad_medida_singular'	=> 'Infografía',	'unidad_medida_plural'	=>'	Infografías'],
            ['unidad_medida_singular'	=> 'Información',	'unidad_medida_plural'	=>'	Informaciones'],
            ['unidad_medida_singular'	=> 'Informe',	'unidad_medida_plural'	=>'	Informes'],
            ['unidad_medida_singular'	=> 'Infraestructura',	'unidad_medida_plural'	=>'	Infraestructuras'],
            ['unidad_medida_singular'	=> 'Ingreso',	'unidad_medida_plural'	=>'	Ingresos'],
            ['unidad_medida_singular'	=> 'Iniciativa',	'unidad_medida_plural'	=>'	Iniciativas'],
            ['unidad_medida_singular'	=> 'Inmuebles',	'unidad_medida_plural'	=>'	Inmuebles'],
            ['unidad_medida_singular'	=> 'Innovación',	'unidad_medida_plural'	=>'	Innovaciones'],
            ['unidad_medida_singular'	=> 'Inscripción',	'unidad_medida_plural'	=>'	Inscripciones'],
            ['unidad_medida_singular'	=> 'Inserción',	'unidad_medida_plural'	=>'	Inserciones'],
            ['unidad_medida_singular'	=> 'Inspección',	'unidad_medida_plural'	=>'	Inspecciones'],
            ['unidad_medida_singular'	=> 'Instalación',	'unidad_medida_plural'	=>'	Instalaciones'],
            ['unidad_medida_singular'	=> 'Institución',	'unidad_medida_plural'	=>'	Instituciones'],
            ['unidad_medida_singular'	=> 'Instructor',	'unidad_medida_plural'	=>'	Instructors'],
            ['unidad_medida_singular'	=> 'Instrumento',	'unidad_medida_plural'	=>'	Instrumentos'],
            ['unidad_medida_singular'	=> 'Insumo',	'unidad_medida_plural'	=>'	Insumos'],
            ['unidad_medida_singular'	=> 'Interno',	'unidad_medida_plural'	=>'	Internos'],
            ['unidad_medida_singular'	=> 'Intervención',	'unidad_medida_plural'	=>'	Intervenciones'],
            ['unidad_medida_singular'	=> 'Inversión',	'unidad_medida_plural'	=>'	Inversiones'],
            ['unidad_medida_singular'	=> 'Investigación',	'unidad_medida_plural'	=>'	Investigaciones'],
            ['unidad_medida_singular'	=> 'Investigador',	'unidad_medida_plural'	=>'	Investigadores'],
            ['unidad_medida_singular'	=> 'Invitación',	'unidad_medida_plural'	=>'	Invitaciones'],
            ['unidad_medida_singular'	=> 'Itinerario',	'unidad_medida_plural'	=>'	Itinerarios'],
            ['unidad_medida_singular'	=> 'Jabón',	'unidad_medida_plural'	=>'	Jabones'],
            ['unidad_medida_singular'	=> 'Jornada',	'unidad_medida_plural'	=>'	Jornadas'],
            ['unidad_medida_singular'	=> 'Jornada/Torneo',	'unidad_medida_plural'	=>'	Jornada/Torneos'],
            ['unidad_medida_singular'	=> 'Jornal',	'unidad_medida_plural'	=>'	Jornaleros'],
            ['unidad_medida_singular'	=> 'Jornalero',	'unidad_medida_plural'	=>'	Jornaleros'],
            ['unidad_medida_singular'	=> 'Joven',	'unidad_medida_plural'	=>'	Jovens'],
            ['unidad_medida_singular'	=> 'Juez',	'unidad_medida_plural'	=>'	Jueces'],
            ['unidad_medida_singular'	=> 'Juicio',	'unidad_medida_plural'	=>'	Juicios'],
            ['unidad_medida_singular'	=> 'Kilogramo',	'unidad_medida_plural'	=>'	Kilogramos'],
            ['unidad_medida_singular'	=> 'Kilómetro Cuadrado',	'unidad_medida_plural'	=>'	Kilómetros cuadrados'],
            ['unidad_medida_singular'	=> 'Kit',	'unidad_medida_plural'	=>'	Kits'],
            ['unidad_medida_singular'	=> 'Laboratorio',	'unidad_medida_plural'	=>'	Laboratorios'],
            ['unidad_medida_singular'	=> 'Laudo',	'unidad_medida_plural'	=>'	Laudos'],
            ['unidad_medida_singular'	=> 'Legitimación',	'unidad_medida_plural'	=>'	Legitimaciones'],
            ['unidad_medida_singular'	=> 'Levantamiento Topográfico',	'unidad_medida_plural'	=>'	Levantamientos topográficos'],
            ['unidad_medida_singular'	=> 'Ley',	'unidad_medida_plural'	=>'	Leyes'],
            ['unidad_medida_singular'	=> 'Libro',	'unidad_medida_plural'	=>'	Libros'],
            ['unidad_medida_singular'	=> 'Licencia',	'unidad_medida_plural'	=>'	Licencias'],
            ['unidad_medida_singular'	=> 'Liga',	'unidad_medida_plural'	=>'	Ligas'],
            ['unidad_medida_singular'	=> 'Línea',	'unidad_medida_plural'	=>'	Líneas'],
            ['unidad_medida_singular'	=> 'Lineamiento',	'unidad_medida_plural'	=>'	Lineamientos'],
            ['unidad_medida_singular'	=> 'Litros',	'unidad_medida_plural'	=>'	Litros'],
            ['unidad_medida_singular'	=> 'Litros Por Segundo',	'unidad_medida_plural'	=>'	Litros Por Segundo'],
            ['unidad_medida_singular'	=> 'Llamada',	'unidad_medida_plural'	=>'	Llamadas'],
            ['unidad_medida_singular'	=> 'Localidad',	'unidad_medida_plural'	=>'	Localidades'],
            ['unidad_medida_singular'	=> 'Locatario',	'unidad_medida_plural'	=>'	Locatarios'],
            ['unidad_medida_singular'	=> 'Lote',	'unidad_medida_plural'	=>'	Lotes'],
            ['unidad_medida_singular'	=> 'Lugar',	'unidad_medida_plural'	=>'	Lugares'],
            ['unidad_medida_singular'	=> 'Madre Soltera',	'unidad_medida_plural'	=>'	Madres solteras'],
            ['unidad_medida_singular'	=> 'Mandamiento',	'unidad_medida_plural'	=>'	Mandamientos'],
            ['unidad_medida_singular'	=> 'Manifestación',	'unidad_medida_plural'	=>'	Manifestaciones'],
            ['unidad_medida_singular'	=> 'Mantenimiento',	'unidad_medida_plural'	=>'	Mantenimientos'],
            ['unidad_medida_singular'	=> 'Manual',	'unidad_medida_plural'	=>'	Manuales'],
            ['unidad_medida_singular'	=> 'Mapa Curricular',	'unidad_medida_plural'	=>'	Mapas curriculares'],
            ['unidad_medida_singular'	=> 'Mastografía',	'unidad_medida_plural'	=>'	Mastografías'],
            ['unidad_medida_singular'	=> 'Material',	'unidad_medida_plural'	=>'	Materiales'],
            ['unidad_medida_singular'	=> 'Matrícula',	'unidad_medida_plural'	=>'	Matrículas'],
            ['unidad_medida_singular'	=> 'Mecanismo',	'unidad_medida_plural'	=>'	Mecanismos'],
            ['unidad_medida_singular'	=> 'Medalla',	'unidad_medida_plural'	=>'	Medallas'],
            ['unidad_medida_singular'	=> 'Medicamento',	'unidad_medida_plural'	=>'	Medicamentos'],
            ['unidad_medida_singular'	=> 'Medición',	'unidad_medida_plural'	=>'	Mediciones'],
            ['unidad_medida_singular'	=> 'Médico',	'unidad_medida_plural'	=>'	Médicos'],
            ['unidad_medida_singular'	=> 'Médico General',	'unidad_medida_plural'	=>'	Médicos Generales'],
            ['unidad_medida_singular'	=> 'Medida',	'unidad_medida_plural'	=>'	Medidas'],
            ['unidad_medida_singular'	=> 'Medio',	'unidad_medida_plural'	=>'	Medios'],
            ['unidad_medida_singular'	=> 'Mejoramiento',	'unidad_medida_plural'	=>'	Mejoramientos'],
            ['unidad_medida_singular'	=> 'Memoria',	'unidad_medida_plural'	=>'	Memorias'],
            ['unidad_medida_singular'	=> 'Mes',	'unidad_medida_plural'	=>'	Meses'],
            ['unidad_medida_singular'	=> 'Mesa De Trabajo',	'unidad_medida_plural'	=>'	Mesa De Trabajos'],
            ['unidad_medida_singular'	=> 'Meta',	'unidad_medida_plural'	=>'	Metas'],
            ['unidad_medida_singular'	=> 'Metro Cuadrado',	'unidad_medida_plural'	=>'	Metro Cuadrados'],
            ['unidad_medida_singular'	=> 'Metro Cúbico',	'unidad_medida_plural'	=>'	Metro Cúbicos'],
            ['unidad_medida_singular'	=> 'Metro Lineal',	'unidad_medida_plural'	=>'	Metro Lineals'],
            ['unidad_medida_singular'	=> 'Microgramo',	'unidad_medida_plural'	=>'	Microgramos'],
            ['unidad_medida_singular'	=> 'Microperforado',	'unidad_medida_plural'	=>'	Microperforados'],
            ['unidad_medida_singular'	=> 'Migrante',	'unidad_medida_plural'	=>'	Migrantes'],
            ['unidad_medida_singular'	=> 'Miles De Millones',	'unidad_medida_plural'	=>'	Miles De Millones'],
            ['unidad_medida_singular'	=> 'Millón De M3',	'unidad_medida_plural'	=>'	Millón De M3s'],
            ['unidad_medida_singular'	=> 'Millones De Dólares',	'unidad_medida_plural'	=>'	Millones De Dólares'],
            ['unidad_medida_singular'	=> 'Ministración',	'unidad_medida_plural'	=>'	Ministraciones'],
            ['unidad_medida_singular'	=> 'Ministración Pagada',	'unidad_medida_plural'	=>'	Ministración Pagadas'],
            ['unidad_medida_singular'	=> 'Minuta',	'unidad_medida_plural'	=>'	Minutas'],
            ['unidad_medida_singular'	=> 'Minuto',	'unidad_medida_plural'	=>'	Minutos'],
            ['unidad_medida_singular'	=> 'Mobiliario',	'unidad_medida_plural'	=>'	Mobiliarios'],
            ['unidad_medida_singular'	=> 'Modelo Dual',	'unidad_medida_plural'	=>'	Modelo Dual'],
            ['unidad_medida_singular'	=> 'Modificación',	'unidad_medida_plural'	=>'	Modificaciones'],
            ['unidad_medida_singular'	=> 'Módulo',	'unidad_medida_plural'	=>'	Módulos'],
            ['unidad_medida_singular'	=> 'Monitoreo',	'unidad_medida_plural'	=>'	Monitoreos'],
            ['unidad_medida_singular'	=> 'Monografía',	'unidad_medida_plural'	=>'	Monografías'],
            ['unidad_medida_singular'	=> 'Movimiento',	'unidad_medida_plural'	=>'	Movimientos'],
            ['unidad_medida_singular'	=> 'Muestra',	'unidad_medida_plural'	=>'	Muestras'],
            ['unidad_medida_singular'	=> 'Mujer',	'unidad_medida_plural'	=>'	Mujers'],
            ['unidad_medida_singular'	=> 'Municipio',	'unidad_medida_plural'	=>'	Municipios'],
            ['unidad_medida_singular'	=> 'Nacimiento',	'unidad_medida_plural'	=>'	Nacimientos'],
            ['unidad_medida_singular'	=> 'Negocio',	'unidad_medida_plural'	=>'	Negocios'],
            ['unidad_medida_singular'	=> 'Niña',	'unidad_medida_plural'	=>'	Niñas'],
            ['unidad_medida_singular'	=> 'Niño',	'unidad_medida_plural'	=>'	Niños'],
            ['unidad_medida_singular'	=> 'Nómina',	'unidad_medida_plural'	=>'	Nóminas'],
            ['unidad_medida_singular'	=> 'Norma',	'unidad_medida_plural'	=>'	Normas'],
            ['unidad_medida_singular'	=> 'Norma Jurídica',	'unidad_medida_plural'	=>'	Norma Jurídicas'],
            ['unidad_medida_singular'	=> 'Normatividad',	'unidad_medida_plural'	=>'	Normatividades'],
            ['unidad_medida_singular'	=> 'Nota',	'unidad_medida_plural'	=>'	Notas'],
            ['unidad_medida_singular'	=> 'Notificación',	'unidad_medida_plural'	=>'	Notificaciones'],
            ['unidad_medida_singular'	=> 'Novillero',	'unidad_medida_plural'	=>'	Novilleros'],
            ['unidad_medida_singular'	=> 'Núcleo',	'unidad_medida_plural'	=>'	Núcleos'],
            ['unidad_medida_singular'	=> 'Número',	'unidad_medida_plural'	=>'	Números'],
            ['unidad_medida_singular'	=> 'Objetivo',	'unidad_medida_plural'	=>'	Objetivos'],
            ['unidad_medida_singular'	=> 'Obra',	'unidad_medida_plural'	=>'	Obras'],
            ['unidad_medida_singular'	=> 'Observación',	'unidad_medida_plural'	=>'	Observaciones'],
            ['unidad_medida_singular'	=> 'Oferta',	'unidad_medida_plural'	=>'	Ofertas'],
            ['unidad_medida_singular'	=> 'Oficio',	'unidad_medida_plural'	=>'	Oficios'],
            ['unidad_medida_singular'	=> 'Olimpiada',	'unidad_medida_plural'	=>'	Olimpiadas'],
            ['unidad_medida_singular'	=> 'Operador',	'unidad_medida_plural'	=>'	Operadors'],
            ['unidad_medida_singular'	=> 'Operativo',	'unidad_medida_plural'	=>'	Operativos'],
            ['unidad_medida_singular'	=> 'Opinión',	'unidad_medida_plural'	=>'	Opiniones'],
            ['unidad_medida_singular'	=> 'Orden',	'unidad_medida_plural'	=>'	Órdenes'],
            ['unidad_medida_singular'	=> 'Ordenamiento',	'unidad_medida_plural'	=>'	Ordenamientos'],
            ['unidad_medida_singular'	=> 'Orientación',	'unidad_medida_plural'	=>'	Orientaciones'],
            ['unidad_medida_singular'	=> 'Paciente',	'unidad_medida_plural'	=>'	Pacientes'],
            ['unidad_medida_singular'	=> 'Padre',	'unidad_medida_plural'	=>'	Padres'],
            ['unidad_medida_singular'	=> 'Padrón',	'unidad_medida_plural'	=>'	Padrones'],
            ['unidad_medida_singular'	=> 'Página Web',	'unidad_medida_plural'	=>'	Páginas Web'],
            ['unidad_medida_singular'	=> 'Pago',	'unidad_medida_plural'	=>'	Pagos'],
            ['unidad_medida_singular'	=> 'Panteón',	'unidad_medida_plural'	=>'	Panteones'],
            ['unidad_medida_singular'	=> 'Paquete',	'unidad_medida_plural'	=>'	Paquetes'],
            ['unidad_medida_singular'	=> 'Participación',	'unidad_medida_plural'	=>'	Participaciones'],
            ['unidad_medida_singular'	=> 'Participante',	'unidad_medida_plural'	=>'	Participantes'],
            ['unidad_medida_singular'	=> 'Pase',	'unidad_medida_plural'	=>'	Pases'],
            ['unidad_medida_singular'	=> 'Patente',	'unidad_medida_plural'	=>'	Patentes'],
            ['unidad_medida_singular'	=> 'Patrulla',	'unidad_medida_plural'	=>'	Patrullas'],
            ['unidad_medida_singular'	=> 'Película',	'unidad_medida_plural'	=>'	Películas'],
            ['unidad_medida_singular'	=> 'Percepción',	'unidad_medida_plural'	=>'	Percepciones'],
            ['unidad_medida_singular'	=> 'Periódico',	'unidad_medida_plural'	=>'	Periódicos'],
            ['unidad_medida_singular'	=> 'Permisos',	'unidad_medida_plural'	=>'	Permisos'],
            ['unidad_medida_singular'	=> 'Persona',	'unidad_medida_plural'	=>'	Personas'],
            ['unidad_medida_singular'	=> 'Pesos',	'unidad_medida_plural'	=>'	Pesos'],
            ['unidad_medida_singular'	=> 'Petición',	'unidad_medida_plural'	=>'	Peticiones'],
            ['unidad_medida_singular'	=> 'Pieza',	'unidad_medida_plural'	=>'	Piezas'],
            ['unidad_medida_singular'	=> 'Plan',	'unidad_medida_plural'	=>'	Planes'],
            ['unidad_medida_singular'	=> 'Plan De Estudio',	'unidad_medida_plural'	=>'	Planes de estudio'],
            ['unidad_medida_singular'	=> 'Plano',	'unidad_medida_plural'	=>'	Planos'],
            ['unidad_medida_singular'	=> 'Planta',	'unidad_medida_plural'	=>'	Plantas'],
            ['unidad_medida_singular'	=> 'Planta De Tratamiento De Aguas',	'unidad_medida_plural'	=>'	Planta de Tratamiento de Aguas'],
            ['unidad_medida_singular'	=> 'Plantel',	'unidad_medida_plural'	=>'	Planteles'],
            ['unidad_medida_singular'	=> 'Plántula',	'unidad_medida_plural'	=>'	Plántulas'],
            ['unidad_medida_singular'	=> 'Plataforma',	'unidad_medida_plural'	=>'	Plataformas'],
            ['unidad_medida_singular'	=> 'Plática',	'unidad_medida_plural'	=>'	Pláticas'],
            ['unidad_medida_singular'	=> 'Plaza',	'unidad_medida_plural'	=>'	Plazas'],
            ['unidad_medida_singular'	=> 'Población',	'unidad_medida_plural'	=>'	Población'],
            ['unidad_medida_singular'	=> 'Polígono',	'unidad_medida_plural'	=>'	Polígonos'],
            ['unidad_medida_singular'	=> 'Política',	'unidad_medida_plural'	=>'	Políticas'],
            ['unidad_medida_singular'	=> 'Póliza',	'unidad_medida_plural'	=>'	Pólizas'],
            ['unidad_medida_singular'	=> 'Ponencia',	'unidad_medida_plural'	=>'	Ponencias'],
            ['unidad_medida_singular'	=> 'Porcentaje',	'unidad_medida_plural'	=>'	Porcentajes'],
            ['unidad_medida_singular'	=> 'Posición',	'unidad_medida_plural'	=>'	Posiciones'],
            ['unidad_medida_singular'	=> 'Pozo',	'unidad_medida_plural'	=>'	Pozos'],
            ['unidad_medida_singular'	=> 'Prácticas',	'unidad_medida_plural'	=>'	Prácticas'],
            ['unidad_medida_singular'	=> 'Predio',	'unidad_medida_plural'	=>'	Predios'],
            ['unidad_medida_singular'	=> 'Prestador',	'unidad_medida_plural'	=>'	Prestadors'],
            ['unidad_medida_singular'	=> 'Presupuesto',	'unidad_medida_plural'	=>'	Presupuestos'],
            ['unidad_medida_singular'	=> 'Prioridades',	'unidad_medida_plural'	=>'	Prioridades'],
            ['unidad_medida_singular'	=> 'Prisión Preventiva',	'unidad_medida_plural'	=>'	Prisión Preventivas'],
            ['unidad_medida_singular'	=> 'Procedimiento',	'unidad_medida_plural'	=>'	Procedimientos'],
            ['unidad_medida_singular'	=> 'Proceso',	'unidad_medida_plural'	=>'	Procesos'],
            ['unidad_medida_singular'	=> 'Producción',	'unidad_medida_plural'	=>'	Producciones'],
            ['unidad_medida_singular'	=> 'Producto',	'unidad_medida_plural'	=>'	Productos'],
            ['unidad_medida_singular'	=> 'Producto Turístico',	'unidad_medida_plural'	=>'	Producto Turísticos'],
            ['unidad_medida_singular'	=> 'Productor',	'unidad_medida_plural'	=>'	Productores'],
            ['unidad_medida_singular'	=> 'Productoras',	'unidad_medida_plural'	=>'	Productoras'],
            ['unidad_medida_singular'	=> 'Profesionista',	'unidad_medida_plural'	=>'	Profesionistas'],
            ['unidad_medida_singular'	=> 'Profesor',	'unidad_medida_plural'	=>'	Profesores'],
            ['unidad_medida_singular'	=> 'Programa',	'unidad_medida_plural'	=>'	Programas'],
            ['unidad_medida_singular'	=> 'Programa Educativo',	'unidad_medida_plural'	=>'	Programa Educativos'],
            ['unidad_medida_singular'	=> 'Promedio',	'unidad_medida_plural'	=>'	Promedios'],
            ['unidad_medida_singular'	=> 'Promoción',	'unidad_medida_plural'	=>'	Promociones'],
            ['unidad_medida_singular'	=> 'Promotor',	'unidad_medida_plural'	=>'	Promotors'],
            ['unidad_medida_singular'	=> 'Propuesta',	'unidad_medida_plural'	=>'	Propuestas'],
            ['unidad_medida_singular'	=> 'Protocolo',	'unidad_medida_plural'	=>'	Protocolos'],
            ['unidad_medida_singular'	=> 'Proyecto',	'unidad_medida_plural'	=>'	Proyectos'],
            ['unidad_medida_singular'	=> 'Pruebas',	'unidad_medida_plural'	=>'	Pruebas'],
            ['unidad_medida_singular'	=> 'Publicación',	'unidad_medida_plural'	=>'	Publicaciones'],
            ['unidad_medida_singular'	=> 'Puntaje',	'unidad_medida_plural'	=>'	Puntajes'],
            ['unidad_medida_singular'	=> 'Punto',	'unidad_medida_plural'	=>'	Puntos'],
            ['unidad_medida_singular'	=> 'Puntos Del Índice',	'unidad_medida_plural'	=>'	Puntos del Índice'],
            ['unidad_medida_singular'	=> 'Queja',	'unidad_medida_plural'	=>'	Quejas'],
            ['unidad_medida_singular'	=> 'Quirófano',	'unidad_medida_plural'	=>'	Quirófanos'],
            ['unidad_medida_singular'	=> 'Ración',	'unidad_medida_plural'	=>'	Raciones'],
            ['unidad_medida_singular'	=> 'Radiodifusora',	'unidad_medida_plural'	=>'	Radiodifusoras'],
            ['unidad_medida_singular'	=> 'Rampa',	'unidad_medida_plural'	=>'	Rampas'],
            ['unidad_medida_singular'	=> 'Razón',	'unidad_medida_plural'	=>'	Razones'],
            ['unidad_medida_singular'	=> 'Receta',	'unidad_medida_plural'	=>'	Recetas'],
            ['unidad_medida_singular'	=> 'Reclutamiento',	'unidad_medida_plural'	=>'	Reclutamientos'],
            ['unidad_medida_singular'	=> 'Recomendación',	'unidad_medida_plural'	=>'	Recomendaciones'],
            ['unidad_medida_singular'	=> 'Reconocimiento',	'unidad_medida_plural'	=>'	Reconocimientos'],
            ['unidad_medida_singular'	=> 'Recopilación',	'unidad_medida_plural'	=>'	Recopilaciones'],
            ['unidad_medida_singular'	=> 'Recorrido',	'unidad_medida_plural'	=>'	Recorridos'],
            ['unidad_medida_singular'	=> 'Recurso',	'unidad_medida_plural'	=>'	Recursos'],
            ['unidad_medida_singular'	=> 'Red',	'unidad_medida_plural'	=>'	Redes'],
            ['unidad_medida_singular'	=> 'Red De Mujeres',	'unidad_medida_plural'	=>'	Redes de mujeres'],
            ['unidad_medida_singular'	=> 'Red Vecinal',	'unidad_medida_plural'	=>'	Red Vecinales'],
            ['unidad_medida_singular'	=> 'Reencuentro',	'unidad_medida_plural'	=>'	Reencuentros'],
            ['unidad_medida_singular'	=> 'Reforma',	'unidad_medida_plural'	=>'	Reformas'],
            ['unidad_medida_singular'	=> 'Refrendo',	'unidad_medida_plural'	=>'	Refrendos'],
            ['unidad_medida_singular'	=> 'Refugio',	'unidad_medida_plural'	=>'	Refugios'],
            ['unidad_medida_singular'	=> 'Registro',	'unidad_medida_plural'	=>'	Registros'],
            ['unidad_medida_singular'	=> 'Reglamento',	'unidad_medida_plural'	=>'	Reglamentos'],
            ['unidad_medida_singular'	=> 'Rehabilitación',	'unidad_medida_plural'	=>'	Rehabilitaciones'],
            ['unidad_medida_singular'	=> 'Reinsertado',	'unidad_medida_plural'	=>'	Reinsertados'],
            ['unidad_medida_singular'	=> 'Reintegración',	'unidad_medida_plural'	=>'	Reintegraciones'],
            ['unidad_medida_singular'	=> 'Relleno Sanitario',	'unidad_medida_plural'	=>'	Relleno Sanitarios'],
            ['unidad_medida_singular'	=> 'Rendimientos',	'unidad_medida_plural'	=>'	Rendimientos'],
            ['unidad_medida_singular'	=> 'Reporte',	'unidad_medida_plural'	=>'	Reportes'],
            ['unidad_medida_singular'	=> 'Representación',	'unidad_medida_plural'	=>'	Representaciones'],
            ['unidad_medida_singular'	=> 'Requerimiento',	'unidad_medida_plural'	=>'	Requerimientos'],
            ['unidad_medida_singular'	=> 'Requisición',	'unidad_medida_plural'	=>'	Requisiciones'],
            ['unidad_medida_singular'	=> 'Resguardo',	'unidad_medida_plural'	=>'	Resguardos'],
            ['unidad_medida_singular'	=> 'Resolución',	'unidad_medida_plural'	=>'	Resoluciones'],
            ['unidad_medida_singular'	=> 'Resolutivo',	'unidad_medida_plural'	=>'	Resolutivos'],
            ['unidad_medida_singular'	=> 'Reunión',	'unidad_medida_plural'	=>'	Reuniones'],
            ['unidad_medida_singular'	=> 'Revisión',	'unidad_medida_plural'	=>'	Revisiones'],
            ['unidad_medida_singular'	=> 'Revista',	'unidad_medida_plural'	=>'	Revistas'],
            ['unidad_medida_singular'	=> 'Ruta',	'unidad_medida_plural'	=>'	Rutas'],
            ['unidad_medida_singular'	=> 'Salida',	'unidad_medida_plural'	=>'	Salidas'],
            ['unidad_medida_singular'	=> 'Sanción',	'unidad_medida_plural'	=>'	Sanciones'],
            ['unidad_medida_singular'	=> 'Satisfacción',	'unidad_medida_plural'	=>'	Satisfacciones'],
            ['unidad_medida_singular'	=> 'Secuencia Didáctica',	'unidad_medida_plural'	=>'	Secuencias didácticas'],
            ['unidad_medida_singular'	=> 'Seguimiento',	'unidad_medida_plural'	=>'	Seguimientos'],
            ['unidad_medida_singular'	=> 'Segundos',	'unidad_medida_plural'	=>'	Segundos'],
            ['unidad_medida_singular'	=> 'Semáforo',	'unidad_medida_plural'	=>'	Semáforos'],
            ['unidad_medida_singular'	=> 'Sentencia',	'unidad_medida_plural'	=>'	Sentencias'],
            ['unidad_medida_singular'	=> 'Sentencias',	'unidad_medida_plural'	=>'	Sentencias'],
            ['unidad_medida_singular'	=> 'Señal',	'unidad_medida_plural'	=>'	Señales'],
            ['unidad_medida_singular'	=> 'Señalética',	'unidad_medida_plural'	=>'	Señaléticas'],
            ['unidad_medida_singular'	=> 'Servicio',	'unidad_medida_plural'	=>'	Servicios'],
            ['unidad_medida_singular'	=> 'Servicio Social',	'unidad_medida_plural'	=>'	Servicios Sociales'],
            ['unidad_medida_singular'	=> 'Servidor',	'unidad_medida_plural'	=>'	Servidores'],
            ['unidad_medida_singular'	=> 'Sesión',	'unidad_medida_plural'	=>'	Sesiones'],
            ['unidad_medida_singular'	=> 'Simulacro',	'unidad_medida_plural'	=>'	Simulacros'],
            ['unidad_medida_singular'	=> 'Sistema',	'unidad_medida_plural'	=>'	Sistemas'],
            ['unidad_medida_singular'	=> 'Sistematización',	'unidad_medida_plural'	=>'	Sistematizaciones'],
            ['unidad_medida_singular'	=> 'Software',	'unidad_medida_plural'	=>'	Software'],
            ['unidad_medida_singular'	=> 'Solicitante',	'unidad_medida_plural'	=>'	Solicitantes'],
            ['unidad_medida_singular'	=> 'Solicitud',	'unidad_medida_plural'	=>'	Solicitudes'],
            ['unidad_medida_singular'	=> 'Solución',	'unidad_medida_plural'	=>'	Soluciones'],
            ['unidad_medida_singular'	=> 'Somatometría',	'unidad_medida_plural'	=>'	Somatometrías'],
            ['unidad_medida_singular'	=> 'Spot',	'unidad_medida_plural'	=>'	Spots'],
            ['unidad_medida_singular'	=> 'Subíndice',	'unidad_medida_plural'	=>'	Subíndices'],
            ['unidad_medida_singular'	=> 'Subsidio',	'unidad_medida_plural'	=>'	Subsidios'],
            ['unidad_medida_singular'	=> 'Sumario',	'unidad_medida_plural'	=>'	Sumarios'],
            ['unidad_medida_singular'	=> 'Supervisión',	'unidad_medida_plural'	=>'	Supervisiones'],
            ['unidad_medida_singular'	=> 'Tabla',	'unidad_medida_plural'	=>'	Tablas'],
            ['unidad_medida_singular'	=> 'Taller',	'unidad_medida_plural'	=>'	Talleres'],
            ['unidad_medida_singular'	=> 'Tanque',	'unidad_medida_plural'	=>'	Tanques'],
            ['unidad_medida_singular'	=> 'Tasa',	'unidad_medida_plural'	=>'	Tasas'],
            ['unidad_medida_singular'	=> 'Técnico',	'unidad_medida_plural'	=>'	Técnicos'],
            ['unidad_medida_singular'	=> 'Televidente',	'unidad_medida_plural'	=>'	Televidentes'],
            ['unidad_medida_singular'	=> 'Tema',	'unidad_medida_plural'	=>'	Temas'],
            ['unidad_medida_singular'	=> 'Terapia',	'unidad_medida_plural'	=>'	Terapias'],
            ['unidad_medida_singular'	=> 'Término De Referencia',	'unidad_medida_plural'	=>'	Términos De Referencia'],
            ['unidad_medida_singular'	=> 'Terreno',	'unidad_medida_plural'	=>'	Terrenos'],
            ['unidad_medida_singular'	=> 'Tiraje',	'unidad_medida_plural'	=>'	Tirajes'],
            ['unidad_medida_singular'	=> 'Tonelada',	'unidad_medida_plural'	=>'	Toneladas'],
            ['unidad_medida_singular'	=> 'Trabajadores',	'unidad_medida_plural'	=>'	Trabajadores'],
            ['unidad_medida_singular'	=> 'Trabajo',	'unidad_medida_plural'	=>'	Trabajos'],
            ['unidad_medida_singular'	=> 'Trámite',	'unidad_medida_plural'	=>'	Trámites'],
            ['unidad_medida_singular'	=> 'Transferencia',	'unidad_medida_plural'	=>'	Transferencias'],
            ['unidad_medida_singular'	=> 'Transmisión',	'unidad_medida_plural'	=>'	Transmisiones'],
            ['unidad_medida_singular'	=> 'Traslado',	'unidad_medida_plural'	=>'	Traslados'],
            ['unidad_medida_singular'	=> 'Trasplante',	'unidad_medida_plural'	=>'	Trasplantes'],
            ['unidad_medida_singular'	=> 'Tratamiento',	'unidad_medida_plural'	=>'	Tratamientos'],
            ['unidad_medida_singular'	=> 'Tríptico',	'unidad_medida_plural'	=>'	Trípticos'],
            ['unidad_medida_singular'	=> 'Turista',	'unidad_medida_plural'	=>'	Turistas'],
            ['unidad_medida_singular'	=> 'Tutor',	'unidad_medida_plural'	=>'	Tutors'],
            ['unidad_medida_singular'	=> 'Tutoría',	'unidad_medida_plural'	=>'	Tutorías'],
            ['unidad_medida_singular'	=> 'Unidad',	'unidad_medida_plural'	=>'	Unidades'],
            ['unidad_medida_singular'	=> 'Usuario',	'unidad_medida_plural'	=>'	Usuarios'],
            ['unidad_medida_singular'	=> 'Utilitario',	'unidad_medida_plural'	=>'	Utilitarios'],
            ['unidad_medida_singular'	=> 'Vacante',	'unidad_medida_plural'	=>'	Vacantes'],
            ['unidad_medida_singular'	=> 'Vacuna',	'unidad_medida_plural'	=>'	Vacunas'],
            ['unidad_medida_singular'	=> 'Validación',	'unidad_medida_plural'	=>'	Validaciones'],
            ['unidad_medida_singular'	=> 'Valoración',	'unidad_medida_plural'	=>'	Valoraciones'],
            ['unidad_medida_singular'	=> 'Variación',	'unidad_medida_plural'	=>'	Variaciones'],
            ['unidad_medida_singular'	=> 'Vehículo',	'unidad_medida_plural'	=>'	Vehículos'],
            ['unidad_medida_singular'	=> 'Verificación',	'unidad_medida_plural'	=>'	Verificaciones'],
            ['unidad_medida_singular'	=> 'Viaje',	'unidad_medida_plural'	=>'	Viajes'],
            ['unidad_medida_singular'	=> 'Víctima',	'unidad_medida_plural'	=>'	Víctimas'],
            ['unidad_medida_singular'	=> 'Video',	'unidad_medida_plural'	=>'	Videos'],
            ['unidad_medida_singular'	=> 'Vinculación',	'unidad_medida_plural'	=>'	Vinculaciones'],
            ['unidad_medida_singular'	=> 'Violación',	'unidad_medida_plural'	=>'	Violaciones'],
            ['unidad_medida_singular'	=> 'Visita',	'unidad_medida_plural'	=>'	Visitas'],
            ['unidad_medida_singular'	=> 'Visitante',	'unidad_medida_plural'	=>'	Visitantes'],
            ['unidad_medida_singular'	=> 'Vivero',	'unidad_medida_plural'	=>'	Viveros'],
            ['unidad_medida_singular'	=> 'Vivienda',	'unidad_medida_plural'	=>'	Viviendas'],
            ['unidad_medida_singular'	=> 'Volumen',	'unidad_medida_plural'	=>'	Volumens'],
            ['unidad_medida_singular'	=> 'Voto',	'unidad_medida_plural'	=>'	Votos'],
            ['unidad_medida_singular'	=> 'Zona',	'unidad_medida_plural'	=>'	Zonas'],
        ];

        DB::table('unidad_medidas')->insert($unidad_medidas);
    }
}
